version: '3.1'
services:
  statistic-server:
    build: statistic-service/statistic-server
    image: statistic-service-image
    container_name: statistic-service-container
    ports:
      - "9090:9090"
    depends_on:
      - statistic-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistic-db:5432/statistic-db

  statistic-db:
    image: postgres:14-alpine
    container_name: statistic-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistic-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  main-service:
    ports:
      - "8080:8080"
    environment:
      - STATISTIC_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:14-alpine
